# Generated by Django 4.1.3 on 2022-11-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_image', models.ImageField(upload_to='blog_images/')),
                ('event_date', models.TextField()),
                ('event_title', models.CharField(max_length=300)),
                ('event_text', models.CharField(max_length=300)),
            ],
        ),
    ]
